### ISSUE TITLE
Missing "./wire" specifier in "@bufbuild/protobuf" package

### ISSUE THREAD

**Issue by jonavos** [bufbuild/protobuf-es#978]
As of this morning (20/9), all of our builds, CI & local, are failing with the above message.

The full error is:
```
vite v4.5.3 building for development...
transforming...
✓ 50 modules transformed.
[commonjs--resolver] Missing "./wire" specifier in "@bufbuild/protobuf" package
✓ built in 1.88s
error during build:
Error: Missing "./wire" specifier in "@bufbuild/protobuf" package
    at e (file:///home/runner/01/_work/redacted/webpage/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:21445:25)
    at n (file:///home/runner/01/_work/redacted/webpage/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:21445:627)
    at o (file:///home/runner/01/_work/redacted/webpage/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:21445:1297)
    at resolveExportsOrImports (file:///home/runner/01/_work/redacted/webpage/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:28746:20)
    at resolveDeepImport (file:///home/runner/01/_work/redacted/webpage/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:28765:31)
    at tryNodeResolve (file:///home/runner/01/_work/redacted/webpage/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:28453:20)
    at Object.resolveId (file:///home/runner/01/_work/redacted/webpage/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:28212:28)
    at file:///home/runner/01/_work/redacted/webpage/node_modules/rollup/dist/es/shared/node-entry.js:25539:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///home/runner/01/_work/redacted/webpage/node_modules/rollup/dist/es/shared/node-entry.js:25439:28)
    at async resolveId (file:///home/runner/01/_work/redacted/webpage/node_modules/rollup/dist/es/shared/node-entry.js:24112:26)
```

Googling doesn't seem to yield any results. And it doesn't appear to be a change on our part as rerunning a successful job from yesterday fails today.

Any help would be appreciated. Thanks.

**Comment by jonavos** [comment]
We resolved this by pinning the version of `buf.build/community/stephenh-ts-proto` to `v1.178.0`.

It was updated yesterday and that appears to have broken our usage.

**Comment by timostamm** [comment]
Hey Jon, it looks like Vite v4 does not support package.json exports yet. The limitation is most likely in Rollup, not Vite itself. It might very well be possible to fix the issue by updating to a more recent version of `@rollup/plugin-node-resolve`.
